apiVersion: v1
kind: Pod
metadata:
  name: hello-target
  labels:
    app: hello-target

spec:
  containers:
  - image: ImageName:ImageTag   #imageName:imageTag 
    name : hello-target
    env:
    - name: ENABLE_CUSTOM_METRICS
      value: "true"
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "50Mi"
      requests:
        cpu: 200m
    ports:
    - containerPort: 80



